# Generated by Django 4.2.3 on 2023-08-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_remove_taskmodel_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
